<?php
$YuRui = [];
// 区域国家三级联动
$YuRui[] = array(
    'url'=>'/student/Homepage/getCityList',
    'name'=>'区域-国家三级联动列表',
    'type'=>'post',
    'data'=>"{'parentid':0}",
    'tip'=>"{'parentid':'可选 选取国家列表不传，获取下级列表传id'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
	    						'id': '当前参数id',
	    						'name': '名称',
                             'en_name': '英文名称',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/searchCourseOrTeacher
',
    'name'=>'学生端-课程-课程或老师搜索',
    'type'=>'post',
    'data'=>"{'search':'关键字','searchtype':1,'pagenum':1}",
    'tip'=>"{'search':'需要搜索的关键字','searchtype':'1课程搜索2老师搜索','pagenum':'当前页数'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'tagid': '标签id',
                             'courseid': '课程id',
                            'coursename': '课程名称',
                            'subhead': '课程副标题',
                            'imageurl': '课程图片',
                            'price': '132.00',
                            'maxprice': '246.00',
                            'classtypes': '开班类型 1 录播课 2直播课',
                            'giftdescribe': '课程概述',
                            'teachername': '老师名称',
                            'profile': '老师简介 暂不用此字段',
                            'classesnum': '暂不用此字段',
                            'imageurl': '暂不用此字段',
                            'recommend': '暂不用此字段',
                            'teacherid': '老师id',
                            'identphoto': '证件照片',
                            'slogan': '老师介绍语',
                            'student_num': '暂不用此字段'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/register',
    'name'=>'学生端-官网首页-提交注册',
    'type'=>'post',
    'data'=>"{'mobile':18235102743,'code':'1234','organid':1,'password':'1234567','prphone':'86'}",
    'tip'=>"{'mobile':'手机号','code':'短信验证码','organid':'机构id;官方首页默认1','password':'密码','prphone':'手机国家区号'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/getUserFavorCategory',
    'name'=>'学生端-注册-查询感兴趣的分类',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
	    						'categoryid': '分类id',
	    						'name': '分类名称',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/addUserFavorCategory',
    'name'=>'学生端-注册-添加学生的分类',
    'type'=>'post',
    'data'=>"{'categoryid':1}",
    'tip'=>"{'categoryid':'分类id'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/getUserTag',
    'name'=>'学生端-注册-查询学生标签',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
	    						'fathername': '主标签',
	    						'childname': '子标签',
	    						'tagid': '主标签id',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/addUserTag',
    'name'=>'学生端-注册-添加学生标签',
    'type'=>'post',
    'data'=>"{'tagid':1,'childtags':'1,2'}",
    'tip'=>"{'tagid':'父标签id','childtags':'子标签id集合,逗号隔开'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
                           }",
);
// 首页->首页机构信息
$YuRui[] = array(
    'url'=>'/student/Homepage/getOrganInfo',
    'name'=>'学生端-官网首页-获取机构相关信息',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'id': '机构id',
                            'organname': '机构名称',
                            'profile': 'profile',
                            'info': '机构概述',
                            'imageurl': '机构logo',
                            'hotline': '客服热线',
                            'email': '客服邮箱',
                            'domain': '域名简写',
                            'summary': '简介',
                            'url': '域名'
                           }",
);
// 首页->首页轮播图
$YuRui[] = array(
    'url'=>'/student/Homepage/getSlideList',
    'name'=>'学生端-官网首页-轮播图',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'id': '轮播图片id',
                            'remark': '图片备注',
                            'imagepath': 'imagepath',
                            'sortid': '顺序',
                            'urltype': '跳转 类型（1：课程id 2：老师id 3：其他）',
                            'teacherid': '老师id',
                            'courseid':'课程id',
                            'url': '其他',
                           }",
);
// 首页->首页分类
$YuRui[] = array(
    'url'=>'/student/Homepage/getCategoryList',
    'name'=>'学生端-官方首页-全部课程分类',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'category_id': '分类id',
                            'categoryname': '分类名称',
                            'rank': '分类等级',
                            'fatherid': '上级分类id',
                            'sort': '排序',
                            'child': '[]下级分类List'
                           }",
);
/*// 首页->首页分类
$YuRui[] = array(
    'url'=>'/student/Homepage/getChildList',
    'name'=>'学生端-机构or官方首页-查询分类子分类',
    'type'=>'post',
    'data'=>"{'organid':1,'categoryid':1}",
    'tip'=>"{'organid':'必选 机构id;官方首页机构id:默认1','categoryid':'必选 分类id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'category_id': '分类id',
                            'categoryname': '分类名称',
                            'rank': '分类等级',
                            'fatherid': '上级分类id',
                            'sort': '排序',
                            'child': '[]下级分类List'
                           }",
);*/
// 首页->热门推荐
$YuRui[] = array(
    'url'=>'/student/HomePage/getRecommendCourser',
    'name'=>'学生端-官网首页-热门推荐',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'subhead': '课程副标题',
                            'imageurl': '课程图片',
                            'coursename': '课程名称',
                            'courseid': '课程id 用于跳转到课程详情',
                            'price': '课程最低价格',
                            'maxprice': '课程最大价格',
                            'giftdescribe': '赠品描述',
                            'classtypes': '1 录播课 2直播课',
                           }",
);
//首页->中部课程及分类
/*$YuRui[] = array(
    'url'=>'/student/HomePage/getChildOrList',
    'name'=>'学生端-机构or官网首页-中部课程及分类展示',
    'type'=>'post',
    'data'=>"{'organid':2}",
    'tip'=>"{'organid':'必选 机构id;官方首页机构id:默认1'}",
    'returns'=>"{  
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'category_id': '一级分类id',
                            'categoryname': '分类名称',
                            'rank': '分类等级',
                            'fatherid': '父级id',
                            'sort': '顺序',
                            'child': '二级分类list',
                            'category_id': '二级分类id',
                            'categoryname': '分类名称',
                            'rank': '分类等级',
                            'fatherid': '父级id',
                            'sort': '顺序',
                            'data': '一级分类id',
                            'curriculumid': '课程id',
                            'type':'班级类型 1是一对一 2是小课班 3是大课班',
                            'totalprice': '课时总价',
                            'teachername': '老师名称',
                            'imageurl': '课程图片',
                            'coursename': '课程名称',
                            'scheduid': '班级排课id 用于跳转到课程详情',
                            'subhead': '课程副标题'
                           }",
);
// 首页->查询分类下的数据
$YuRui[] = array(
    'url'=>'/student/HomePage/getCategorySchedu',
    'name'=>'学生端-机构or官方首页-查询分类下的班级',
    'type'=>'post',
    'data'=>"{'organid':1,'categoryid':1}",
    'tip'=>"{'organid':'必选 机构id;官方首页机构id:默认1','categoryid':'分类id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'curriculumid': '课程id',
                            'type':'班级类型 1是一对一 2是小课班 3是大课班',
                            'totalprice': '课时总价',
                            'teachername': '老师名称',
                            'imageurl': '课程图片',
                            'coursename': '课程名称',
                            'scheduid': '班级排课id 用于跳转到课程详情',
                            'subhead': '课程副标题'
                           }",
);*/
// 首页->名师推荐
$YuRui[] = array(
    'url'=>'/student/Homepage/getRecommendTeacher',
    'name'=>'学生端-机构首页-名师推荐',
    'type'=>'post',
    'data'=>"{'organid':1}",
    'tip'=>"{'organid':'必选 机构id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'teachername': '老师名称',
                            'profile': '老师简介 暂不用此字段',
                            'classesnum': '暂不用此字段',
                            'imageurl': '暂不用此字段',
                            'recommend': '暂不用此字段',
                            'teacherid': '老师id',
                            'identphoto': '证件照片',
                            'slogan': '老师介绍语',
                            'student_num': '暂不用此字段'
                           }",
);
// 首页->分类查询
$YuRui[] = array(
    'url'=>'/student/Homepage/getFilterCourserList',
    'name'=>'学生端-官方首页-查询分类下的课程',
    'type'=>'post',
    'data'=>"{'is_free':0,'category_id':'1','pagenum':'1','limit':'2','coursetype':1}",
    'tip'=>"{'is_free':'是否查询免费学。0:全部.1:免费','category_id':'可选默认不填类型:数字','pagenum':'分页页码 ','limit':'取出多少条记录','coursetype':'可选1 录播课 2直播课'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'pageinfo':'分页list',
                            'pagesize':'每页多少条记录',
                            'pagenum':'当前页码',
                            'total':'总记录数',
                            'categorylist': '分类List',
                            'category_id': '分类id' ,
                            'categoryname': '分类名称',
                            'rank': '分类等级',
                            'fatherid': '父类id',
                            'sort': '排序id',
                            'subhead': '课程副标题',
                            'imageurl': '课程图片',
                            'coursename': '课程名称',
                            'courseid': '课程id 用于跳转到课程详情',
                            'price': '课程最低价格',
                            'maxprice': '课程最大价格',
                            'classtypes': '课程类型 1 录播课 2直播课'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/getCateLeader',
    'name'=>'学生端-官方首页-分类搜索导航和面包屑',
    'type'=>'post',
    'data'=>"{'category_id':1,'organid':1}",
    'tip'=>"{'category_id':'必选 分类id','organid':'1'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'id': '分类id',
                            'title': '分类名称',
                            'rank': '分类等级',
                            'fid': '父级id',
                            'children':'下集分类',
                            'selected':'是否选中 true:选中; false:未选中',
                            'leader': '面包屑'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Curriculumdetail/getCurriculumDateList',
    'name'=>'学生端-官方首页-课程详情返回可选日期',
    'type'=>'post',
    'data'=>"{'courseid':1}",
    'tip'=>"{'courseid':1}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Curriculumdetail/getCurriculumInfo',
    'name'=>'学生端-官网-课程详情列表',
    'type'=>'post',
    'data'=>"{'courseid':2,'classtypes':2,'teacherid':1,'date':'2018-07-06','fullpeople':4}",
    'tip'=>"{'courseid':'课程id','classtypes':'1 录播课 2直播课','teacherid':'老师id 可选参数 默认不传','date':'日期','fullpeople':'可选默认0 4或者6'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'category': '分类List',
                            'tags': '课程标签 官方的没有此List',
                            'applystatus':'报名状态0不可报名1可报名',
                            'timestr': '日期',
                            'courser': '课程相关信息list',
                            'curriculumid': '课程id',
                            'organid': '机构id',
                            'scheduid': '排课班级id',                
                            'teacherid': '老师id',
                            'type': '班级类型 1:一对一2：小班课3：大班课',
                            'totalprice': '课时总价',
                            'gradename': '班级名称',
                            'teachername': '老师姓名',
                            'imageurl': '课程封面图',
                            'coursename': '课程名称',
                            'subhead': '课程副标题',
                            'describe': '适用人群描述',
                            'studypeople': '学习人数',
                            'periodnum': '课时总数',
                            'generalize': '课程概述',
                            'teacher': '授课老师信息list',
                            'imageurl': '老师头像',
                            'classesnum': '开课数量',
                            'studentnum': '学生数量',
                            'teachername': '老师姓名',
                            'unit': '课时安排list',
                            'unitid': '单元id',
                            'curriculumid': 2,
                            'unitname': '单元名称',
                            'unitsort': '单元排序',
                            'period': '课节list',
                            'periodname': '课节名称',
                            'periodsort': 1,
                            'intime': '上课时间年月日',
                            'time': '上课时间时分秒',
                            'recommend': '老师推荐课程list',
                            'curriculumid': '课程id',
                            'type': '班级类型1：一对一2：小班课 3：大班课',
                            'totalprice': '课时总价',
                            'teachername': '老师姓名',
                            'imageurl': '课程封面图',
                            'coursename': '课程名称',
                            'scheduid': '班级id',
                            'organinfo': '机构list 官方网站有次list',
                            'imageurl': '机构图片',
                            'organid': '机构id',
                            'organname': '机构名称',
                            'summary': '机构简介',
                            'phone': '机构电话',
                            'email': '机构email',
                            'realnum': '报名人数',
                            'vip': '0'
                        }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/randomCode',
    'name'=>'学生端-找回密码、注册-随机图形验证码',
    'type'=>'post',
    'data'=>"",
    'tip'=>"{}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
	    						'codeimg': 'data:image/png;base64流文件',
                             'sessionid': '验证码的标识'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/sendMobileMsg',
    'name'=>'学生端-找回密码、注册-发送短信',
    'type'=>'post',
    'data'=>"{'mobile':18235102743,'code':'1234','organid':1,'sessionid':'54444444444','type':1,'prphone':'86'}",
    'tip'=>"{'mobile':'手机号','code':'图形验证码','organid':'机构id','sessionid':'随机验证码返回的验证码标识','type':'业务类型 1找回密码 2 注册','prphone':'默认不传'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/updatePass',
    'name'=>'学生端-找回密码-找回密码',
    'type'=>'post',
    'data'=>"{'mobile':18235102743,'code':'1234','organid':1,'newpass':'1234567'}",
    'tip'=>"{'mobile':'手机号','code':'短信验证码','organid':'机构id','newpass':'新密码'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/updateUserPass',
    'name'=>'学生端-个人资料-修改密码',
    'type'=>'post',
    'data'=>"{'mobile':18235102743,'code':'1234','organid':1,'newpass':'1234567'}",
    'tip'=>"{'mobile':'手机号','code':'短信验证码','organid':'机构id','newpass':'新密码'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/getAllTeacherList',
    'name'=>'学生端-官网首页-名师堂',
    'type'=>'post',
    'data'=>"{'pagenum':1}",
    'tip'=>"{'pagenum':'分页页数'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'teacherid': '老师id',
                            'imageurl': '老师头像',
                            'prphone': '手机号前缀',
                            'mobile': '手机号',
                            'teachername': '真实姓名',
                            'nickname': '昵称',
                            'accountstatus': '暂不用',
                            'addtime': '暂不用',
                            'sex': '性别 0保密 1男 2女',
                            'country': '国家',
                            'province': '省',
                            'city': '城市',
                            'profile': '简介',
                            'birth': '暂不用',
                            'age': '年龄',
                            'classnum': '开班数量',
                            'student': '学生数量',
                            'score': '评分',
                            'lable': '老师标签List',
                            'tagname': '老师名称',
                            'is_collection':'如果是官方首页,需要此字段;是否收藏过该老师的标识',
                            'organinfo':'如果是官方首页,需要此字段;机构详情list',
                            'imageurl': '机构Logo',
                            'organid': '机构id，用于查看机构详情',
                            'organname': '机构名称',
                            'summary': '机构简介',
                            'phone': '机构电话',
                            'email': '机构邮箱',
                            'vip': '暂不用此字段'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Teacherdetail/getTeacherCurriculum',
    'name'=>'学生端-官网首页-老师个人信息',
    'type'=>'post',
    'data'=>"{'teacherid':1}",
    'tip'=>"{'teacherid':'老师id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'teacherid': '老师id',
                            'imageurl': '老师头像',
                            'prphone': '手机号前缀',
                            'mobile': '手机号',
                            'teachername': '真实姓名',
                            'nickname': '昵称',
                            'accountstatus': '暂不用',
                            'addtime': '暂不用',
                            'sex': '性别 0保密 1男 2女',
                            'country': '国家',
                            'province': '省',
                            'city': '城市',
                            'profile': '简介',
                            'birth': '暂不用',
                            'age': '年龄',
                            'classnum': '开班数量',
                            'student': '学生数量',
                            'score': '评分',
                            'lable': '老师标签List',
                            'tagname': '老师名称',
                            'is_collection':'如果是官方首页,需要此字段;是否收藏过该老师的标识',
                            'organinfo':'如果是官方首页,需要此字段;机构详情list',
                            'imageurl': '机构Logo',
                            'organid': '机构id，用于查看机构详情',
                            'organname': '机构名称',
                            'summary': '机构简介',
                            'phone': '机构电话',
                            'email': '机构邮箱',
                            'vip': '暂不用此字段'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Teacherdetail/getTeacherClass',
    'name'=>'学生端-官网首页-Ta的班级',
    'type'=>'post',
    'data'=>"{'teacherid':1,'classtype':0}",
    'tip'=>"{'teacherid':'老师id','classtype':'课程类型  0免费课程1在售课程'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'subhead': '课程副标题',
                            'imageurl': '课程图片',
                            'coursename': '课程名称',
                            'courseid': '课程id 用于跳转到课程详情',
                            'price': '课程最低价格',
                            'maxprice': '课程最大价格',
                            'giftdescribe': '赠品描述',
                            'classtypes': '1 录播课 2直播课',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Teacherdetail/getCommentList',
    'name'=>'学生端-官网首页-Ta的评价',
    'type'=>'post',
    'data'=>"{'teacherid':1,'pagenum':1,'limit':1}",
    'tip'=>"{'teacherid':'老师id','pagenum':'可选分页页数','limit':'每页页数'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'imageurl': '学生邮箱',
                            'nickname': '学生昵称',
                            'addtime': '评论时间',
                            'score': '评分',
                            'content': '评论内容',
                            'commentid': '评论id'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Myorder/gotoOrder',
    'name'=>'学生端-订单-提交订单',
    'type'=>'post',
    'data'=>"{'courseid':5,'studentid':1,'schedulingid':'1','amount':'1.00','ordersource':'1','organid':1,'originprice':'1234567','addressid':1,'usestatus':1,'type':1,'packageid':1,'packagegiftid':1,'packageuseid':1}",
    'tip'=>"{'courseid':'课程id','studentid':'学生登录用户名id','schedulingid':'班级id','amount':'实付金额','ordersource':'下单渠道 1web 2app','organid':'机构id','originprice':'课程原价','addressid':'地址id','usestatus':'是否使用优惠券0未使用1使用','type':'类型','packageid':'套餐id','packagegiftid':'赠送套餐id','packageuseid':'套餐的使用id'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
	    						'discount': '优惠金额',
	    						'originprice': '课程总价',
	    						'amount': '实付金额',
	    						'ordernum': '订单号',
	    						'usablemoney': '账户余额',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Myorder/queryOrderStatus',
    'name'=>'学生端-订单-去支付',
    'type'=>'post',
    'data'=>"{'ordernum':'201804281811553803628717','type':1}",
    'tip'=>"{'ordernum':'订单号','type':'1购买课程2购买套餐'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Myorder/showOrderDetail',
    'name'=>'学生端-订单-支付中心',
    'type'=>'post',
    'data'=>"{'ordernum':'201804281811553803628717'}",
    'tip'=>"{'ordernum':'订单号'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'orderid': '订单id',
                            'studentid': '学生id',
                            'curriculumid': '课程id',
                            'ordernum': '订单号',
                            'classname': '班级名称',
                            'coursename': '课程名称',
                            'originprice': '课程原价',
                            'discount': '优惠金额',
                            'ordertime': '下单时间',
                            'schedulingid': '班级排课id',
                            'amount': '订单金额',
                            'type': '班级类型 1是一对一 2是小班 3是大班',
                            'organid': '机构id',
                            'orderstatus': '订单状态',
                            'teachername': '老师姓名',
                            'imageurl': '课程图片',
                            'usablemoney': '学生可用余额'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Myorder/gotoPay',
    'name'=>'学生端-订单-立即支付',
    'type'=>'post',
    'data'=>"{'ordernum':'201808272126369803894011','studentid':1,'paytype':'2'}",
    'tip'=>"{'ordernum':'订单号','studentid':'学生id','paytype':'如果是单一支付方式：0其他，1余额，2微信，3支付宝，4银联'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            '如果是支付宝支付': '跳转到支付宝页面',
                            '如果是微信支付': '会返回codeurl字段 用于支付扫码的url',
                            '如果是余额支付': '会返回成功失败的消息',
                       }",
);
$YuRui[] = array(
    'url'=>'/student/User/getStudentInfo',
    'name'=>'学生端-个人资料-个人信息',
    'type'=>'post',
    'data'=>"{'studentid':'1'}",
    'tip'=>"{'studentid':'学生id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'usablemoney': '账户余额',
                            'birth': '出生年月日',
                            'id': '学生id',
                            'username': '真实姓名',
                            'prphone': '手机前缀',
                            'mobile': '18235102743',
                            'nickname': '昵称',
                            'sex': '性别 0保密 1男 2女',
                            'country': '国家',
                            'province': '省',
                            'city': '城市',
                            'profile': '学生简介',
                            'year': '出生年',
                            'month': '出生月',
                            'date': '出生日'
                       }",
);
$YuRui[] = array(
    'url'=>'/student/User/getStudentPaylog',
    'name'=>'学生端-个人资料-账户明细',
    'type'=>'post',
    'data'=>"{'studentid':'1','pagenum':1,'limit':1}",
    'tip'=>"{'studentid':'学生id','pagenum':'可选分页页数','limit':'每页页数'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'pageinfo': '分页list', 
                            'pagesize':'每页多少条记录',
                            'pagenum':'当前页码',
                            'total':'总记录数',
                            'coursename': '课程名称',
                            'studentid': 1,
                            'paynum': '金额',
                            'paytype': '支付类型1余额支付2微信支付3支付宝支付4银联支付',
                            'paystatus': '流水类型1：购买课程2：充值3:购买套餐',
                            'paytime': '操作时间'
                       }",
);
$YuRui[] = array(
    'url'=>'/student/User/sendUpdateMobileMsg',
    'name'=>'学生端-个人资料-修改手机号,修改密码发送验证码',
    'type'=>'post',
    'data'=>"{'mobile':'18235102745','organid':1,'prphone':'86'}",
    'tip'=>"{'mobile':'手机号','organid':'机构id','prphone':'手机号国家号'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                       }",
);
$YuRui[] = array(
    'url'=>'/student/User/updateMobile',
    'name'=>'学生端-个人资料-修改手机号',
    'type'=>'post',
    'data'=>"{'oldmobile':'18235102745','prphone':'86','newmobile':'18235102742','code':'123456'}",
    'tip'=>"{'oldmobile':'原来手机号','prphone':'手机号国家区号','newmobile':'新手机号','code':'验证码'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                       }",
);
$YuRui[] = array(
    'url'=>'/student/User/uploadHeadimg',
    'name'=>'学生端-个人资料-上传头像',
    'type'=>'post',
    'data'=>"{}",
    'tip'=>"{'文件key值':'uploadFile'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'source_url': '头像url地址',
                       }",
);
$YuRui[] = array(
    'url'=>'/student/User/updateStudentInfo',
    'name'=>'学生端-个人资料-编辑资料',
    'type'=>'post',
    'data'=>"{'imageurl':'url','nickname':'12','sex':0,'country':23,'province':13,'city':56,'birth':'2018-3-5','profile':'简介','studentid':'1'}",
    'tip'=>"{'imageurl':'学生头像链接',
				    			'nickname':'昵称',
				    			'sex':'性别id',
				    			'country':'国家id',
				    			'province':'省份id',
				    			'city':'城市id',
				    			'birth':'2018-3-5',
				    			'profile':'简介',
				    			'studentid':'学生用户id'
				    		}",
    'returns'=>"{
			    				        'code': '返回的查询标识,0为正常返回,其他为异常',
			    						'data': '最外层data为此次请求的返回数据',
			    						'info': '此次请求返回数据描述',
		                            }",
);
$YuRui[] = array(
    'url'=>'/student/User/studentRecharge',
    'name'=>'学生端-个人资料-充值',
    'type'=>'post',
    'data'=>"{'amount':'1.00','paytype':'2','source':1}",
    'tip'=>"{'amount':'订单金额','paytype':'支付类型 2:微信支付3支付宝4银联','source':'充值渠道1pc 2手机'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            '如果是支付宝支付': '跳转到支付宝页面',
                            '如果是微信支付': '会返回codeurl字段 用于支付扫码的url',
                          
                       }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/studentCourseList',
    'name'=>'学生端-我的课表-我的课表',
    'type'=>'post',
    'data'=>"{'date':'2018-05-02'}",
    'tip'=>"{'date':'当前年月'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
	    						'timestr': '日期',
	    						'year': '年',
                                'month': '月',
                                'day': '日',
                                'num': '这个日期有多少节课',
                                '':'第一层数组键代表返回数据的周，内层数据的键代表周几，比如周一就是1'
                       }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/getLessonsByDate',
    'name'=>'学生端-我的课表-单日课程列表',
    'type'=>'post',
    'data'=>"{'date':'2018-09-08'}",
    'tip'=>"{'date':'需要获取课程列表对应的日期'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'schedulingid': '排课id',
                                'organid': '机构id',
                                'intime': '2018-05-09',
                                'timekey': '33,34',
                                'coursename': '课程名称',
                                'type': '班型',
                                'teacherid': 1,
                                'toteachid': 7,
                                'periodname': '课节名称',
                                'periodsort': '课节排序id',
                                'curriculumid': '课程id',
                                'classhour': '课节时长',
                                'lessonsid': '课节id',
                                'teachername': '老师名称',
                                'buttonstatus': '定义按钮状态  0 未开始 1进教室 2 去评价 回放 3回放',
                                'starttime': '2018-05-09 16:30:00',
                                'endtime': '2018-05-09 17:30:00'
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/gotoComment',
    'name'=>'学生端-我的课表-评价',
    'type'=>'post',
    'data'=>"{'nickname':'测试','curriculumid':1,'classtype':1,'studentid':1,'teacherid':1,'score':1,'schedulingid':1,'content':'评论呢','lessonsid':1}",
    'tip'=>"{'nickname':'学生昵称','curriculumid':1,'classtype':'课程类型1录播课2直播课','studentid':'学生id','teacherid':'老师id','score':1,'schedulingid':'排课id 可选','content':'评论呢'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/intoClassroom',
    'name'=>'学生端-我的课表-进教室',
    'type'=>'post',
    'data'=>"{'toteachid':1}",
    'tip'=>"{'toteachid':'预约时间id'}",
    'returns'=>"{
                              'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'teachername': '老师名称',
                                'url': '进入教室的url'
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/getLessonsPlayback',
    'name'=>'学生端-我的课表-回放',
    'type'=>'post',
    'data'=>"{'toteachid':1}",
    'tip'=>"{'toteachid':'预约时间id'}",
    'returns'=>"{
                              'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'teachername': '老师名称',
                                'starttime': '上课时间',
                                'lessonsname': '课节名称',
                                'video':'视频片段list' ,
                                'playpath': '视频片段url',
                                'https_playpath': '视频https片段',
                                'duration': '时长时分秒',
                                'part': '片段编号1,2'
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/getBuyCurriculum',
    'name'=>'学生端-我的课程-我的课程列表',
    'type'=>'post',
    'data'=>"{'studentid':1,'pagenum':1,'limit':1,'coursetype':1}",
    'tip'=>"{'studentid':'学生id','pagenum':'分页页数','limit':'每页记录数','coursetype':'课程类型1：录播课2直播课'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'pageinfo':'分页list',
                                'pagesize': '每页记录数',
                                'pagenum': '当前页数',
                                'total': '总条数',
                                'schedulingid': '排课id',
                                'teacherid': '老师id',
                                'organid': '机构id',
                                'curriculumid': '课程id',
                                'orderid': '订单id暂且不用',
                                'ordernum': '订单号暂且不用',
                                'classname': '班级名称',
                                'coursename': '课程名称',
                                'ordertime': '下单时间 暂不用',
                                'amount': '暂不用订单金额',
                                'originprice': '课程原价',
                                'type': '班级类型',
                                'orderstatus': '暂不用',
                                'teachername': '老师名称',
                                'imageurl': '课程图片',
                                'subhead': '课程副标题',
                                'reserve': '如果是一对一课程，查看是否预约完毕；1为预约完毕,查看详情0为去约课',
                                'learned': '已学课时100%',
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/getClassSchedule',
    'name'=>'学生端-我的课程-课时安排或查看详情',
    'type'=>'post',
    'data'=>"{'coursetype':1,'schedulingid':'1','courseid':2}",
    'tip'=>"{'coursetype':'1:录播课查看详情2:直播课课时安排','schedulingid':'班级id,可选,如果是','courseid':'课程id'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'curriculumid': '课程id',
                                'organid': '机构id',
                                'scheduid': '排课id',
                                'teacherid': '老师id',
                                'type': '班级类型 1是一对一 2是小课班 3是大课班',
                                'totalprice': '课时总价',
                                'gradename': '班级名称',
                                'teachername': '老师名称',
                                'teacherimg': '老师图片,暂且不用',
                                'imageurl': '课程图片',
                                'coursename': '课程图片',
                                'subhead': '课程副标题',
                                'describe': '适用人群描述',
                                'studypeople': '学生数量 暂且不用',
                                'periodnum': '暂且不用',
                                'categoryid': '暂且不用',
                                'generalize': '课程概述',
                                'unit': '单元List',
                                'unitid': '单元id',
                                'unitname': '单元名称',
                                'unitsort': '单元排序',
                                'period': '课节List',
                                'periodname': '课节名称',
                                'periodsort': '课节排序',
                                'intime': '上课时间年月日',
                                'time': '上课时间时分秒',
                                'lessonsid': '课节id',
                                'toteachid': '预约时间表id'
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/watchPlayback',
    'name'=>'学生端-我的课程-直播课查看课时的视频',
    'type'=>'post',
    'data'=>"{'lessonsid':1,'courseid':1,'studentid':1}",
    'tip'=>"{'lessonsid':'课时id','courseid':'课程id','studentid':'学生id'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'fileurl': '文件url',
                                'iscomment': '学生评论标识1已经评论0未评论'
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/getRecordComment',
    'name'=>'学生端-我的课程-查看录播课课时评论',
    'type'=>'post',
    'data'=>"{'lessonsid':1,'pagenum':1}",
    'tip'=>"{'lessonsid':'课时id','pagenum':'分页页数'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'imageurl': '学生邮箱',
                                'nickname': '学生昵称',
                                'addtime': '评论时间',
                                'score': '评分',
                                'content': '评论内容',
                                'commentid': '评论id'
                            }",
);
/*$YuRui[] = array(
    'url'=>'/student/Mycourse/getLessionsList',
    'name'=>'学生端-我的课程-去约课',
    'type'=>'post',
    'data'=>"{'organid':1,'studentid':1,'schedulingid':1,'ordernum':'201805211636507069483518'}",
    'tip'=>"{'organid':'机构id','studentid':'学生id','schedulingid':'排课id','ordernum':'订单号'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'unitid': '单元id',
                                'curriculumid': '课程id',
                                'unitname': '单元名称',
                                'unitsort': '单元排序',
                                'period':'课节list',
                                'lessonsid': '课节id',
                                'periodname': '课节名称',
                                'periodsort': '课节排序',
                                'intime': '预约年月日',
                                'time': '预约时分秒',
                                'toteachid': '预约时间表id',
                                'reservebuttons': '预约或修改状态 预约 1修改 2.不显示按钮',
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/getFreeList',
    'name'=>'学生端-我的课程-查询老师空闲时间',
    'type'=>'post',
    'data'=>"{'date':'2018-05-02','teacherid':1,'organid':1}",
    'tip'=>"{'date':'时间年月日如果不传默认当天时间','teacherid':'老师id从上一页面带到当前页面','organid':'机构id从上一页面带入'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'data': '05:30老师可预约时间值'
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/addEdit',
    'name'=>'学生端-我的课程-修改或预约时间',
    'type'=>'post',
    'data'=>"{'schedulingid':1,'intime':'2018-05-17','studentid':1,'timekey':16,'lessonsid':1,'toteachid':1,'organid':1,'ordernum':'201805211636507069483518'}",
    'tip'=>"{'schedulingid':'排课id','intime':'预约时间年月日','studentid':'学生id','timekey':'时间key','lessonsid':'课节id','toteachid':'时间表id没有传空字符串','organid':'机构id','ordernum':'订单号'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述'
                            }",
);*/
$YuRui[] = array(
    'url'=>'/student/Myorder/getMyOrderList',
    'name'=>'学生端-我的订单-我的订单列表',
    'type'=>'post',
    'data'=>"{'pagenum':1,'limit':1}",
    'tip'=>"{'pagenum':'分页页数','limit':'每页记录数'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'pageinfo':'分页list',
                            'pagesize': '每页记录数',
                            'pagenum': '当前页数',
                            'total': '总记录数',
                            'data': '数据list',
                            'schedulingid': '排课id',
                            'teacherid': '老师id',
                            'organid': '机构id',
                            'curriculumid': '课程Id',
                            'orderid': '订单id',
                            'ordernum': '订单号',
                            'classname': '班级名称',
                            'coursename': '课程名称',
                            'ordertime': '下单时间',
                            'amount': '订单金额',
                            'originprice': '课程原价',
                            'type': '班级类型',
                            'orderstatus': '订单状态0已下单，1超时未支付已取消状态，2已支付，3申请退款',
                            'teachername': '老师名称',
                            'imageurl': '课程图片',
                            'subhead': '课程简介'
                       }",
);
$YuRui[] = array(
    'url'=>'/student/Myorder/orderQuery',
    'name'=>'学生端-我的订单-微信查询订单状态',
    'type'=>'post',
    'data'=>"{'ordernum':'201804281944329376183807'}",
    'tip'=>"{'ordernum':'订单号'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'data': '05:30老师可预约时间值',
                                'trade_state': 'SUCCESS:支付成功;PAYERROR:支付失败;USERPAYING:用户支付中;NOTPAY:等待支付状态;CLOSED:已关闭;REVOKED:已撤销',
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Myorder/cancelOrder',
    'name'=>'学生端-我的订单-取消订单',
    'type'=>'post',
    'data'=>"{'ordernum':'201804281944329376183807'}",
    'tip'=>"{'ordernum':'订单号'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                                'data': '05:30老师可预约时间值'
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Myorder/orderSuccess',
    'name'=>'学生端-订单-订单成功详情',
    'type'=>'post',
    'data'=>"{'ordernum':'201804281811553803628717'}",
    'tip'=>"{'ordernum':'订单号'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'orderid': '订单id',
                            'studentid': '学生id',
                            'curriculumid': '课程id',
                            'ordernum': '订单号',
                            'classname': '班级名称',
                            'coursename': '课程名称',
                            'originprice': '课程原价',
                            'discount': '优惠金额',
                            'ordertime': '下单时间',
                            'schedulingid': '班级排课id',
                            'amount': '订单金额',
                            'type': '班级类型 1是一对一 2是小班 3是大班',
                            'organid': '机构id',
                            'orderstatus': '订单状态',
                            'teachername': '老师姓名',
                            'imageurl': '课程图片',
                            'balance': '余额支付部分',
                            'teacherimage': '老师头像',
                            'paytype': '支付方式0其他，1余额，2微信，3支付宝，4银联',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/teacherCollect',
    'name'=>'学生端-官网首页-收藏老师',
    'type'=>'post',
    'data'=>"{'teacherid':1,'studentid':5}",
    'tip'=>"{'teacherid':'老师id','studentid':'学生id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/cancelTeacherCollect',
    'name'=>'学生端-官网首页-取消收藏老师',
    'type'=>'post',
    'data'=>"{'teacherid':1,'studentid':5}",
    'tip'=>"{'teacherid':'老师id','studentid':'学生id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/classCollect',
    'name'=>'学生端-官网首页-收藏课程班级',
    'type'=>'post',
    'data'=>"{'courseid':1,'studentid':5}",
    'tip'=>"{'courseid':'课程id','studentid':'学生id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/cancelClassCollect',
    'name'=>'学生端-官网首页-取消收藏课程班级',
    'type'=>'post',
    'data'=>"{'courseid':1,'studentid':5}",
    'tip'=>"{'courseid':'课程id','studentid':'学生id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/teacherCollectList',
    'name'=>'学生端-首页-我的老师收藏列表',
    'type'=>'post',
    'data'=>"{'studentid':5,'pagenum':1,'limit':10}",
    'tip'=>"{'studentid':'学生id','pagenum':'分页页数','limit':'每页记录数'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'imageurl': '老师照片',
                            'profile': '老师简介',
                            'teachername': '老师姓名',
                            'teacherid': '老师id'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/classCollectList',
    'name'=>'学生端-首页-我的课程收藏列表',
    'type'=>'post',
    'data'=>"{'studentid':5,'pagenum':1,'limit':10}",
    'tip'=>"{'studentid':'学生id','pagenum':'分页页数','limit':'每页记录数'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'curriculumid': '课程id',
                            'organid': '机构id',
                            'scheduid': '班级id',
                            'teacherid': '老师id',
                            'type': '班级类型',
                            'totalprice': '课时总价',
                            'gradename': '班级名称',
                            'imageurl': '课程图片',
                            'teachername': '老师名称'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/sendUpdateMobileMsg',
    'name'=>'学生端-首页-领取免费课程发送短信',
    'type'=>'post',
    'data'=>"{'mobile':18235102722,'prphone':86}",
    'tip'=>"{'mobile':'手机号','prphone':'手机号前缀'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/addReceiveInfo',
    'name'=>'学生端-首页-领取免费课程表单提交',
    'type'=>'post',
    'data'=>"{'mobile':18235102722,'prphone':86,'code':123456,'name':'昵称'}",
    'tip'=>"{'mobile':'手机号','prphone':'手机号前缀','code':'手机验证码','name':'昵称'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/getPackageList',
    'name'=>'学生端-首页-查询我的套餐列表',
    'type'=>'post',
    'data'=>"{'pagenum':1}",
    'tip'=>"{'pagenum':'分页页数'}",
    'returns'=>"{
                             'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'packageid': '套餐id',
                            'bughour': '购买课时数量',
                            'setmeal': '套餐名称',
                            'setimgpath': '套餐封面url',
                            'setprice': '套餐价格',
                            'limitbuy': '限购次数（0：无限购，其他限购次数）',
                            'threshold': '使用门槛 0 无限制 其他代表满够金额',
                            'efftype': '有效期状态（1：时间范围 2：固定天数）',
                            'effendtime': '时间范围维度下的开始时间',
                            'effstarttime': '时间范围维度下的结束时间',
                            'efftime': '固定天数 维度下的时间',
                            'trialtype': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'content': '使用内容',
                            'givestatus': '是否赠送课时（0：不赠送 1：赠送) 如果为1 赠送套餐的详情需要展示',
                            'sendvideo': '赠送录播课（0：未赠送 其他：赠送录播s课时间',
                            'sendlive': '赠送直播课（0：未赠送 其他：赠送直播s课时间）',
                            'giftthreshold': '使用门槛 0 无限制 其他代表满够金额',
                            'giftefftype': '赠送课时的有效期状态（1：时间范围 2：固定天数）',
                            'gifteffstarttime': '时间范围维度下的开始时间',
                            'gifteffendtime':'时间范围维度下的结束时间',
                            'giftefftime': '购买后到期天数',
                            'gifttrialtype': '可使用课程（0：全部课程，1：指定分类，2：指定课程）',
                            'packagegiftid': '赠送课时的id'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/getPackageDetail',
    'name'=>'学生端-首页-查询我的套餐详情',
    'type'=>'post',
    'data'=>"{'packageid':1}",
    'tip'=>"{'packageid':'套餐id'}",
                            'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'packageid': '套餐id',
                            'bughour': '购买课时数量',
                            'setmeal': '套餐名称',
                            'setimgpath': '套餐封面url',
                            'setprice': '套餐价格',
                            'limitbuy': '限购次数（0：无限购，其他限购次数）',
                            'threshold': '使用门槛 0 无限制 其他代表满够金额',
                            'efftype': '有效期状态（1：时间范围 2：固定天数）',
                            'effendtime': '时间范围维度下的开始时间',
                            'effstarttime': '时间范围维度下的结束时间',
                            'efftime': '固定天数 维度下的时间',
                            'trialtype': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'content': '使用内容',
                            'givestatus': '是否赠送课时（0：不赠送 1：赠送) 如果为1 赠送套餐的详情需要展示',
                            'sendvideo': '赠送录播课（0：未赠送 其他：赠送录播s课时间',
                            'sendlive': '赠送直播课（0：未赠送 其他：赠送直播s课时间）',
                            'giftthreshold': '使用门槛 0 无限制 其他代表满够金额',
                            'giftefftype': '赠送课时的有效期状态（1：时间范围 2：固定天数）',
                            'gifteffstarttime': '时间范围维度下的开始时间',
                            'gifteffendtime':'时间范围维度下的结束时间',
                            'giftefftime': '购买后到期天数',
                            'gifttrialtype': '可使用课程（0：全部课程，1：指定分类，2：指定课程）',
                            'packagegiftid': '赠送课时的id'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Package/gotoOrder',
    'name'=>'学生端-首页-套餐下单',
    'type'=>'post',
    'data'=>"{'packageid':1,'ordersource':'1'}",
    'tip'=>"{'packageid':1,'ordersource':'下单渠道 1web 2app'}",
    'returns'=>"{
                             'code': '返回的查询标识，0为正常返回，其他为异常',
                             'data': '最外层data为此次请求的返回数据',
                             'info': '此次请求返回数据描述',
                             'ordernum': '201809071531153651275622'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Package/showOrderDetail',
    'name'=>'学生端-首页-显示套餐详情',
    'type'=>'post',
    'data'=>"{'ordernum':'201809071531153651275622'}",
    'tip'=>"{}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'packageid': '套餐id',
                            'bughour': '购买课时数量',
                            'setmeal': '套餐名称',
                            'setimgpath': '套餐封面url',
                            'setprice': '套餐价格',
                            'limitbuy': '限购次数（0：无限购，其他限购次数）',
                            'threshold': '使用门槛 0 无限制 其他代表满够金额',
                            'efftype': '有效期状态（1：时间范围 2：固定天数）',
                            'effendtime': '时间范围维度下的开始时间',
                            'effstarttime': '时间范围维度下的结束时间',
                            'efftime': '固定天数 维度下的时间',
                            'trialtype': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'content': '使用内容',
                            'givestatus': '是否赠送课时（0：不赠送 1：赠送) 如果为1 赠送套餐的详情需要展示',
                            'sendvideo': '赠送录播课（0：未赠送 其他：赠送录播s课时间',
                            'sendlive': '赠送直播课（0：未赠送 其他：赠送直播s课时间）',
                            'giftthreshold': '使用门槛 0 无限制 其他代表满够金额',
                            'giftefftype': '赠送课时的有效期状态（1：时间范围 2：固定天数）',
                            'gifteffstarttime': '时间范围维度下的开始时间',
                            'gifteffendtime':'时间范围维度下的结束时间',
                            'giftefftime': '购买后到期天数',
                            'gifttrialtype': '可使用课程（0：全部课程，1：指定分类，2：指定课程）',
                            'packagegiftid': '赠送课时的id'
                            'amount': '套餐金额',
                            'orderstatus': '套餐状态',
                            'studentid': '学生id',
                            'ordernum': '订单金额'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Package/gotoPay',
    'name'=>'学生端-首页-套餐支付',
    'type'=>'post',
    'data'=>"{'ordernum':1,'paytype':'1'}",
    'tip'=>"{'ordernum':1,'paytype':'支付方式0其他，1余额，2微信，3支付宝，4银联5贝宝paypal'}",
    'returns'=>"{
                             'code': '返回的查询标识，0为正常返回，其他为异常',
                             'data': '最外层data为此次请求的返回数据',
                             'info': '此次请求返回数据描述',
                             'ordernum': '201809071531153651275622',
                             '如果是支付宝支付': '跳转到支付宝页面',
                             '如果是微信支付': '会返回codeurl字段 用于支付扫码的url',
                             '如果是余额支付': '会返回成功失败的消息',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Package/getPackageOrderList',
    'name'=>'学生端-个人中心-查询套餐订单列表',
    'type'=>'post',
    'data'=>"{'pagenum':1}",
    'tip'=>"{'pagenum':1}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'packageid': '套餐id',
                            'bughour': '购买课时数量',
                            'setmeal': '套餐名称',
                            'setimgpath': '套餐封面url',
                            'setprice': '套餐价格',
                            'limitbuy': '限购次数（0：无限购，其他限购次数）',
                            'threshold': '使用门槛 0 无限制 其他代表满够金额',
                            'efftype': '有效期状态（1：时间范围 2：固定天数）',
                            'effendtime': '时间范围维度下的开始时间',
                            'effstarttime': '时间范围维度下的结束时间',
                            'efftime': '固定天数 维度下的时间',
                            'trialtype': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'content': '使用内容',
                            'givestatus': '是否赠送课时（0：不赠送 1：赠送) 如果为1 赠送套餐的详情需要展示',
                            'sendvideo': '赠送录播课（0：未赠送 其他：赠送录播s课时间',
                            'sendlive': '赠送直播课（0：未赠送 其他：赠送直播s课时间）',
                            'giftthreshold': '使用门槛 0 无限制 其他代表满够金额',
                            'giftefftype': '赠送课时的有效期状态（1：时间范围 2：固定天数）',
                            'gifteffstarttime': '时间范围维度下的开始时间',
                            'gifteffendtime':'时间范围维度下的结束时间',
                            'giftefftime': '购买后到期天数',
                            'gifttrialtype': '可使用课程（0：全部课程，1：指定分类，2：指定课程）',
                            'packagegiftid': '赠送课时的id'
                            'amount': '套餐金额',
                            'orderstatus': '套餐状态',
                            'studentid': '学生id',
                            'ordernum': '订单金额'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Package/cancelOrder',
    'name'=>'学生端-我的套餐订单-取消订单',
    'type'=>'post',
    'data'=>"{'ordernum':'201804281944329376183807'}",
    'tip'=>"{'ordernum':'订单号'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                            }",
);
$YuRui[] = array(
    'url'=>'/student/Package/orderSuccess',
    'name'=>'学生端-套餐订单-订单成功详情',
    'type'=>'post',
    'data'=>"{'ordernum':'201804281811553803628717'}",
    'tip'=>"{'ordernum':'订单号'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'packageid': '套餐id',
                            'bughour': '购买课时数量',
                            'setmeal': '套餐名称',
                            'setimgpath': '套餐封面url',
                            'setprice': '套餐价格',
                            'limitbuy': '限购次数（0：无限购，其他限购次数）',
                            'threshold': '使用门槛 0 无限制 其他代表满够金额',
                            'efftype': '有效期状态（1：时间范围 2：固定天数）',
                            'effendtime': '时间范围维度下的开始时间',
                            'effstarttime': '时间范围维度下的结束时间',
                            'efftime': '固定天数 维度下的时间',
                            'trialtype': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'content': '使用内容',
                            'givestatus': '是否赠送课时（0：不赠送 1：赠送) 如果为1 赠送套餐的详情需要展示',
                            'sendvideo': '赠送录播课（0：未赠送 其他：赠送录播s课时间',
                            'sendlive': '赠送直播课（0：未赠送 其他：赠送直播s课时间）',
                            'giftthreshold': '使用门槛 0 无限制 其他代表满够金额',
                            'giftefftype': '赠送课时的有效期状态（1：时间范围 2：固定天数）',
                            'gifteffstarttime': '时间范围维度下的开始时间',
                            'gifteffendtime':'时间范围维度下的结束时间',
                            'giftefftime': '购买后到期天数',
                            'gifttrialtype': '可使用课程（0：全部课程，1：指定分类，2：指定课程）',
                            'packagegiftid': '赠送课时的id'
                            'amount': '套餐金额',
                            'orderstatus': '套餐状态',
                            'studentid': '学生id',
                            'ordernum': '订单金额'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Package/packageUseList',
    'name'=>'学生端-我的套餐-查询套餐使用状态',
    'type'=>'post',
    'data'=>"{'status':'1','pagenum':1}",
    'tip'=>"{'status':'0待使用 1已使用 2已过期','pagenum':'分页页数'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'packageid': '套餐id',
                            'bughour': '购买课时数量',
                            'setmeal': '套餐名称',
                            'setimgpath': '套餐封面url',
                            'setprice': '套餐价格',
                            'limitbuy': '限购次数（0：无限购，其他限购次数）',
                            'threshold': '使用门槛 0 无限制 其他代表满够金额',
                            'efftype': '有效期状态（1：时间范围 2：固定天数）',
                            'effendtime': '时间范围维度下的开始时间',
                            'effstarttime': '时间范围维度下的结束时间',
                            'efftime': '固定天数 维度下的时间',
                            'trialtype': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'content': '使用内容',
                            'givestatus': '是否赠送课时（0：不赠送 1：赠送) 如果为1 赠送套餐的详情需要展示',
                            'sendvideo': '赠送录播课（0：未赠送 其他：赠送录播s课时间',
                            'sendlive': '赠送直播课（0：未赠送 其他：赠送直播s课时间）',
                            'giftthreshold': '使用门槛 0 无限制 其他代表满够金额',
                            'giftefftype': '赠送课时的有效期状态（1：时间范围 2：固定天数）',
                            'gifteffstarttime': '时间范围维度下的开始时间',
                            'gifteffendtime':'时间范围维度下的结束时间',
                            'giftefftime': '购买后到期天数',
                            'gifttrialtype': '可使用课程（0：全部课程，1：指定分类，2：指定课程）',
                            'packagegiftid': '赠送课时的id',
                            'amount': '套餐金额',
                            'orderstatus': '套餐状态',
                            'studentid': '学生id',
                            'ordernum': '订单金额',
                            'type': '套餐类型 1套餐 2套餐赠送课时',
                            'surplus': '套餐剩余课时数量',
                            'total': '套餐总课时数量',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Package/deletePackageUse',
    'name'=>'学生端-我的套餐订单-删除学生套餐的使用',
    'type'=>'post',
    'data'=>"{'packageuseid':1}",
    'tip'=>"{'packageuseid':'套餐使用的id'}",
    'returns'=>"{
                                'code': '返回的查询标识，0为正常返回，其他为异常',
                                'data': '最外层data为此次请求的返回数据',
                                'info': '此次请求返回数据描述',
                            }",
);
$YuRui[] = array(
    'url'=>'/student/User/addOrUpdateAddress',
    'name'=>'学生端-个人信息-添加或者修改收货地址',
    'type'=>'post',
    'data'=>"{'pid':7,'cityid':'1001','areaid':1002,'address':'红军营南路','linkman':'测试人','mobile':'18235102743','zipcode':'030024','isdefault':0,'id':1}",
    'tip'=>"{'pid':'省id','cityid':'城市id','areaid':'区域id','address':'地址','linkman':'联系人','mobile':'手机号','zipcode':'邮政编码','isdefault':'是否默认地址 1默认0否','id':'可选 修改信息是必选'}",
    'returns'=>"{
	    						'code': '返回的查询标识，0为正常返回，其他为异常',
	    						'data': '最外层data为此次请求的返回数据',
	    						'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/getAddressList',
    'name'=>'学生端-个人信息-查询收货地址',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'studentid': '学生id',
                            'pid': '省id',
                            'cityid': '城市id',
                            'areaid': '区域id',
                            'address': '详细地址',
                            'zipcode': '邮编',
                            'linkman': '联系人',
                            'mobile': '手机号',
                            'isdefault': '1:默认收货地址0否',
                            'pname': '省名称',
                            'cname': '城市名称',
                            'aname': '区域名称'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/deleteAddress',
    'name'=>'学生端-个人信息-删除收货地址',
    'type'=>'post',
    'data'=>"{'id':1}",
    'tip'=>"{'id':'收货地址id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/getHomeworkList',
    'name'=>'学生端-我的作业-我的作业列表',
    'type'=>'post',
    'data'=>"{'pagenum':1,'status':0}",
    'tip'=>"{'pagenum':'分页页数','status':'0未完成 1已完成 2.已批阅'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'homeworkid': '作业编号',
                            'courseid': '课程Id',
                            'classid': '班级id',
                            'lessonid': '课节id',
                            'studentid': '学生id',
                            'submittime': '提交时间',
                            'score': '分数',
                            'coursename': '课程名称',
                            'gradename': '班级名称',
                            'periodname': '课节名称',
                            'teacherid': '老师id',
                            'endtime': '截止时间',
                            'teachername': '老师名称'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/searchHomework',
    'name'=>'学生端-我的作业-搜索',
    'type'=>'post',
    'data'=>"{'pagenum':1,'status':0,'search':'测试'}",
    'tip'=>"{'pagenum':'分页页数','status':'0未完成 1已完成 2.已批阅','search':'搜索名称'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'homeworkid': '作业编号',
                            'courseid': '课程Id',
                            'classid': '班级id',
                            'lessonid': '课节id',
                            'studentid': '学生id',
                            'submittime': '提交时间',
                            'score': '分数',
                            'coursename': '课程名称',
                            'gradename': '班级名称',
                            'periodname': '课节名称',
                            'teacherid': '老师id',
                            'endtime': '截止时间',
                            'teachername': '老师名称'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/getQuestionList',
    'name'=>'学生端-我的作业-写作业查询我的题库',
    'type'=>'post',
    'data'=>"{'lessonid':1095,'classid':1}",
    'tip'=>"{'lessonid':'班级的课时id','classid':'班级id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'subjectid': '对应题库id',
                            'type': '题型(1选择题，2多选题，3填空题，4作文)',
                            'options': '选择题的选项 当type等于1或2的时候用此字段',
                            'courseid': '课程id',
                            'periodid': '课程对应的课时id',
                            'name': '题目名称',
                            'imageurl': '图片url',
                            'analysis': '作文题的解析 用于type为2的',
                            'score': '分值',
                            'periodname': '课时名称',
                            'subject_count': '题目总数',
                            'periodname': '课程的课时名称',
                            'lessonsid': '班级对应的课时id',
                            'lessonsname': '班级对应的课时名称 试卷名称用这个',
                            'totalscore': 1
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/submitQuestions',
    'name'=>'学生端-我的作业-作业提交',
    'type'=>'post',
    'data'=>"{
'answers': [{'subjectid':1,'answer':'测试1'},{'subjectid':2,'answer':'测试2'}],'classid':1,'lessonid':1095,'homeworkid':1

}",
    'tip'=>"{
'answers': [{'subjectid':'题目id','answer':'答案'},{'subjectid':2,'answer':'测试2'}],'classid':'班级id','lessonid':'班级课时id','homeworkid':'作业id'

}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/showUpdateQuestions',
    'name'=>'学生端-我的作业-修改查询作业信息',
    'type'=>'post',
    'data'=>"{'lessonid':1095,'classid':1}",
    'tip'=>"{'lessonid':'班级的课时id','classid':'班级id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'subjectid': '对应题库id',
                            'type': '题型(1选择题，2多选题，3填空题，4作文)',
                            'options': '选择题的选项 当type等于1或2的时候用此字段',
                            'courseid': '课程id',
                            'periodid': '课程对应的课时id',
                            'name': '题目名称',
                            'imageurl': '图片url',
                            'analysis': '作文题的解析 用于type为2的',
                            'score': '分值',
                            'answers':'答案',
                            'periodname': '课时名称',
                            'subject_count': '题目总数',
                            'periodname': '课程的课时名称',
                            'lessonsid': '班级对应的课时id',
                            'lessonsname': '班级对应的课时名称 试卷名称用这个',
                            'totalscore': 1
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/updateQuestions',
    'name'=>'学生端-我的作业-作业修改提交',
    'type'=>'post',
    'data'=>"{
'answers': [{'subjectid':1,'answer':'测试1'},{'subjectid':2,'answer':'测试2'}],'classid':1,'lessonid':1095,'homeworkid':1

}",
    'tip'=>"{
'answers': [{'subjectid':'题目id','answer':'答案'},{'subjectid':2,'answer':'测试2'}],'classid':'班级id','lessonid':'班级课时id','homeworkid':'作业id'

}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/getCompleteQuestionList',
    'name'=>'学生端-我的作业-查询已完成的作业信息',
    'type'=>'post',
    'data'=>"{'lessonid':1095,'classid':1}",
    'tip'=>"{'lessonid':'班级的课时id','classid':'班级id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                            'subjectid': '对应题库id',
                            'type': '题型(1选择题，2多选题，3填空题，4作文)',
                            'options': '选择题的选项 当type等于1或2的时候用此字段',
                            'courseid': '课程id',
                            'periodid': '课程对应的课时id',
                            'name': '题目名称',
                            'imageurl': '图片url',
                            'analysis': '作文题的解析 用于type为2的',
                            'score': '分值',
                            'periodname': '课时名称',
                            'subject_count': '题目总数',
                            'periodname': '课程的课时名称',
                            'lessonsid': '班级对应的课时id',
                            'lessonsname': '班级对应的课时名称 试卷名称用这个',
                            'totalscore': 1
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/sendHomeworkMessage',
    'name'=>'学生端-作业-已完成作业发送消息提醒',
    'type'=>'post',
    'data'=>"{'homeworkid':1}",
    'tip'=>"{'homeworkid':'学生作业id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/User/getFeedbackList',
    'name'=>'学生端-个人信息-分析反馈或搜索',
    'type'=>'post',
    'data'=>"{'pagenum':1,'search':'ceshi'}",
    'tip'=>"{'pagenum':'分页页数','search':'搜索内容 可选 默认不传这个字段'}",
    'returns'=>"{
                           'code': '返回的查询标识，0为正常返回，其他为异常',
                           'data': '最外层data为此次请求的返回数据',
                           'info': '',
                           'periodname':'课时名称',
                           'curriculumname':'课程名称',
                           'gradename':'班级名称',
                           'comment':'评论内容 点击查看用此字段',
                           'score': '分数',
                           'addtime':'添加时间 时间戳',
                           'teachername':'老师名称此次请求返回数据描述',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Myorder/getUserPackage',
    'name'=>'学生端-订单详情-查询学生用户可用的优惠券',
    'type'=>'post',
    'data'=>"{'curriculumid':1,'amount':'1.00'}",
    'tip'=>"{'curriculumid':'课程id','amount':'课程金额或者班级金额'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '',
                            'packageid': '套餐id',
                            'packagegiftid': '赠送套餐优惠券id',
                            'type': '优惠券类型1优惠券2赠送的优惠券',
                            'surplus': '套餐剩余课时数量',
                            'total': '套餐总课时数量',
                            'endtime': '套餐到期时间',
                            'setmeal': '套餐名称',
                            'threshold': '套餐使用门槛',
                            'trialtype': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'categoryids': '分类id集合',
                            'curriculumids': '课程id集合',
                            'gifttrialtype': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'giftcategoryids': '分类集合',
                            'giftcurriculumids': '可使用课程（1：全部课程，2：指定分类，3：指定课程）',
                            'giftthreshold': '赠送套餐套餐使用门槛'
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Mycourse/getAllClassList',
    'name'=>'学生端-调班-查询可调的班级信息和目标班级信息',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '',
                            'schedulingid': '原班级id',
                            'gradename': '原班级名称',
                            'periodnum': '原班级课时数量',
                            'curriculumid': '原班级课程id',
                            'num': '原班级已上课的课时数量',
                            'surplusnum': '原班级剩余课时数量',
                            'classlist': '目标班级list',
                            'schedulingid': '目标班级id',
                            'gradename': '目标班级名称',
                            'teachername': '目标班级老师名称',
                            'starttime': '目标班级开始上课时间',
                            'endtime': '目标班级课程结束时间'
                                           }"
);
$YuRui[] = array(
    'url'=>'student/Mycourse/submitApplyClasss',
    'name'=>'学生端-调班-调班提交',
    'type'=>'post',
    'data'=>"{'curriculumid':1,'oldschedulingid':1,'newschedulingid':2}",
    'tip'=>"{'curriculumid':'课程id','原班级id':1,'newschedulingid':'新班级id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '',
                           }",
);
$YuRui[] = array(
    'url'=>'student/Mycourse/getBuyCourseList',
    'name'=>'学生端-调课-查询课程和原班级信息',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '',
                            'coursename': '课程名称',
                            'curriculumid': '课程id',
                            'classinfo': 
                            'schedulingid': '班级id',
                            'gradename': '班级名称',
                            'periodnum': '课时数量',
                            'curriculumid': '课程id',
                            'lessons': '原班级课时list'
                            'teacherid': '老师id',
                            'teachername': '老师名称',
                            'lessonsid': '班级对应课节id',
                            'periodname': '课时名称',
                            'periodid': '课程对应的课时id'
                            }",
);
$YuRui[] = array(
        'url'=>'student/Mycourse/getSelectableLessons',
    'name'=>'学生端-调课-获取可选择的课时名称',
    'type'=>'post',
    'data'=>"{'lessonsid':1254,'schedulingid':168,'curriculumid':146,'periodid':166}",
    'tip'=>"{'lessonsid':'课时id','schedulingid':'原班级id','curriculumid':'课程id','periodid':'课程对应的课时id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '',
                            'schedulingid': '班级id',
                            'gradename': '班级名称',
                            'teachername': '老师姓名',
                            'starttime': '开始时间',
                            'endtime': '结束时间',
                            'newlessonsid': '目标课时的id',
                            'newteachername': '目标班级的老师姓名'
                            }",
);
$YuRui[] = array(
    'url'=>'student/Mycourse/submitApplylession',
    'name'=>'学生端-调课-调课提交',
    'type'=>'post',
    'data'=>"{'newlessonsid':1254,'oldlessonsid':168,'curriculumid':146}",
    'tip'=>"{'newlessonsid':'新课节id','oldlessonsid':'旧的课节信息','curriculumid':'课程id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '',
                            }",
);
$YuRui[] = array(
    'url'=>'student/Mycourse/getTeacherComment',
    'name'=>'学生端-课时详情-获取老师点评',
    'type'=>'post',
    'data'=>"{'lessonsid':1049}",
    'tip'=>"{'lessonsid':'课节id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '',
                            'periodname': '课时名称',
                            'curriculumname': '课程名称',
                            'gradename': '班级名称',
                            'comment': '评论',
                            'score': '分数',
                            'addtime': '添加时间',
                            'teachername': '老师名称',
                            'imageurl': '老师头像',
                            'status': '该学生是否被评价(0未评价,1已评价)'
                           }",
);
$YuRui[] = array(
    'url'=>'student/Mycourse/getHomeworkByLessionid',
    'name'=>'学生端-课时详情-获取作业信息',
    'type'=>'post',
    'data'=>"{'lessonsid':1049}",
    'tip'=>"{'lessonsid':'课节id'}",
    'returns'=>"{
                            'code': '返回的查询标识，0为正常返回，其他为异常',
                            'data': '最外层data为此次请求的返回数据',
                            'info': '',
                            'issubmited': '是否已提交作业（0未提交，1已提交）',
                            'reviewstatus': '批阅状态(0未批阅,1已批阅)',
                            'homeworkid': '作业id',
                            'courseid': '课程id',
                            'classid': '班级id',
                            'lessonid': '课时id',
                            'studentid': '学生id',
                            'submittime': '提交时间',
                            'score': '分数',
                            'coursename': '课程名称',
                            'gradename': '班级名称',
                            'periodname': '课时名称',
                            'teacherid': '老师id',
                            'endtime': '截止时间',
                           }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/aboutus',
    'name'=>'学生端-首页-关于我们',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
             'aboutus': '关于我们',
        }",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/configureShow',
    'name'=>'学生端-首页-关于我们-配置下载展示',
    'type'=>'post',
    'data'=>"",
    'tip'=>"",
    'returns'=>"{
        'code': 0,
        'data': {
                'qrcodeandroid': '安卓二维码',
                'qrcodeios': 'ios二维码',
                'cloudclasswindows': 'cloudclass windows插件',
                'cloudclassmac': 'cloudclass mac 插件',
                'teamviewwindows': 'teamview windows插件',
                'teamviewmac': 'teamview mac插件',
                'chromewindows': 'chrome windows插件',
                'chromemac': 'chrome mac插件',
                'browser360xp': 'browser360 xp插件'
        },
        'info': '操作成功'
}",
);
$YuRui[] = array(
    'url'=>'/student/Homepage/isdelflag',
    'name'=>'学生端-个人中心-查看课程或者老师是否被删除',
    'type'=>'post',
    'data'=>"{'type':1,'id':'1'}",
    'tip'=>"{'type':'类型 1查看课程是否存在2查看老师是否存在','id':'类型为课程传课程id,类型为老师传老师id'}",
    'returns'=>"{
                'code': '返回的查询标识，0为正常返回，code为35125 表示被删除',
                'data': '最外层data为此次请求的返回数据',
                'info': '',
        }",
);

